language: objective-c
osx_image: xcode9.3
script:
xcodebuild -project WeakItemContainer.xcodeproj -scheme WeakItemContainer -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.3.1' test
